packages:
  - supabase/functions

ignoredBuiltDependencies:
  - esbuild
  - ffmpeg-static
  - msgpackr-extract
  - onnxruntime-node
  - protobufjs
  - puppeteer
  - sharp
  - supabase
  - tesseract.js
